### Login Request
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "juan",
    "password": "12bote34"
}

### Register Request

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "adriana",
    "password": "abril0304",
    "email": "adrianakmontiele@gmail.com"
}

### Logout Request

POST http://localhost:3000/logout

### hasSession Request

POST http://localhost:3000/hasSession
Content-Type: application/json
    
    {
        "token": "eyJhbG"
    }