### Prueba de login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "johndoe",
    "password": "securepassword1" 
}

### Prueba de registro de un nuevo usuario
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "nuevo_usuario",
    "password": "password123",
    "name": "John",
    "lastName": "Doe",
    "phone": "123456789",
    "email": "johndoe@example.com",
    "address": "123 Calle Principal"
}

### Prueba de logout
POST http://localhost:3000/logout
Content-Type: application/json
Cookie: connect.sid=<SESSION_ID> 
